[build]
  functions = "netlify/functions"

# (optional) allow your static site to call the function from any origin
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

